[package]
name = "kafka-producer"
version = "0.1.0"
edition = "2021"

[dependencies]
rdkafka = { version = "0.36.2" }
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"
tokio = { version = "1.40.0", features = ["full"] }
